* Cream of Fiddlehead Soup

** Ingredients

- 3 cups of fiddleheads
- 1 cup of carrots
- 1 cup of onions
- 1 cup of celery
- 1 cups of chicken stock
- 2 tbps of butter
- olive oil
- salt
- pepper
- full fat coconut

** Instuctions

In a heavied bottom pot, add butter/oil combination and begin sauteing
mirepoix until the the onions become translucent. Add chicken stock
and fiddleheads. Season lightly with salt and pepper. Cook on simmer
for 1.5 hrs. With an immersion blender, blitz the coup to your desired
thickness. Add 1 cup of full fat coconut to make it thick and creamy.

Save a couple cooked fiddleheads for garnish. Place 2 or 3 on top of
your soup and lightly drizzle a good olive oil on the soup. Freshly
grind ground pepper and serve.

** Notes

- Leeks and garlic would be a great addition to the mirepoix.
- You can swap out coconut milk with 1 cup of heavy cream.
- Replace chicken stock with vegatable stock to make it vegaterian.
- Veggy stock and olive oil only to make it vegan.
