* Cream of Fiddlehead Soup with Leeks

With Fiddlehead season around the corner, I need to use last years
harvest. Wwhat better way to warm up on a cold and wet spring day
than making soup and a sandwich.

Today's recipe deviates from the standard mirepoix of carrots, onions,
and celery. I didn't have any celery but I did have leeks and
potatoes. This is more of a leek and potato soup than a traditional
Fiddlehead soup but delicious none the less.

** Ingredients

- 2 leeks
- 2 small carrots
- 2 lbs of fiddleheads
- 1/2 a large onion
- 2-3 potatoes
- 2 boxes of reduced salt Chicken stock or roughly 1.8L of water
- 2 knobs of butter
- 2 tablespoons of olive oil
- 1 can of whole fat coconut milk
- salt & pepper to taste
- couple sprigs thyme 

** Instructions

Prepare your mise en place by roughly chopping your vegatables. The
size of your mirepoix will affect the cooking time but size isn't very
important only that they are consistently sized.

Heat a heavy bottom pot on medium  and add your oil and butter. The
butter should efferevese slightly but not brown. The goal is to sweat
the mirepoix until the onions become translucent.

Add your stock along with your potatoes and fiddleheads. Bring the
water to a boil then reduce heat to a simmer. Add thyme saving the
seasoning until the very end. Simmer for 45-60 minutes.

After you've simmered the soup, with an immersion blender blitz to
your desired consistency. I like a smoother texture so I blitz for a
longer period of time.

If you're feeling fancy, save a few cooked fiddleheads for
garnish. Season with freshly ground pepper and sea salt. Drizzel some
extra virgin olive oil.

Enjoy.

** Notes

The soup ended up being a bit over powered by the potatoes and
coconut-- losing a bit of the fiddlehead flavour. Next time around, I
might use less potatos and coconut milk.

An alternative to fiddleheads would be to use asparagus in it's
place. To make vegatarian or vegan, eliminate the butter and chicken
stock and replace with oil and vegatable stock.
