* Apple Cider Pulled Pork

** Ingredients

- 1 large pork butt (aka shoulder)
- 1 box of chicken stock
- 1 large carrot
- 2 Large Onions
- 3 Ribs of celery
- salt
- pepper
- apple cider vinegar 1 cup
- butter
- olive oil
- 2-3 bay leaves

** Optional

- garlic
- dry rub
- hard apple cider

** Instructions

In a large dutch oven brown the pork butt on all sides. Add butter and
olive oil and deglaze the pot with roughly chopped mirepoix. Preheat
the oven to 350. Once the mirepoix starts caramelizing return the meat
back into the pot adding the vinegar and stock to almost cover the
meat. Place the pot into the oven for 3 hrs. Check at around the 2 hr
mark and once the meat is fork tender, it is ready.

** Notes

You can optionally add a dry rub before browning but be careful not to
the burn the spices. It will just make it bitter instead. You can
deglaze with anything acidic or sweet. E.g. Dry wines, hard apple
cider, bourbon, brandy, etc.

** Dishes

*** Pulled Pork Slaw Sliders

Your friends will love you if you serve pulled pork sliders at the
next big sporting event.

Using a mandolin, food processor, or just plain ol' chop red onions, red
and green cabbage, and grate a large carrot. Add one tsp of vinegar, 1
tbsp of sugar, 1/4-1/2 cup of mayonnaise and one heap tbsp of dijon
mustard. Salt and pepper to taste. Let it sit in the fridge for a bit
to mellow out raw spicy flavour of the cabbage and onions.


