* Smoked Salmon Pasta

A friend of mine gave me some smoked salmon over the winter his father
has smoked. I've long since forgotten about it until I did a bit of
cleaning in my freezer.

I normally eat smoked salmon on a cracker with mayo but I decided to
do something different today.

** Ingredients 

- 200g of Spaghetti
- Two smoked salmon tails
- 1 teaspoon Dried dill (Fresh would be better)
- 3  tablespoons of chopped chives
- Lemon
- 2 Tomatos
- 3 Garlic cloves
- 1 Shallots 
- teaspoon Crushed chillis
- Salt and pepper
- Parmesan
- Olive oil

** Instructions

This recipe shouldn't take you anymore than 15-20 minutes to make. Add
water to a large pot, make sure you salt your pasta water. While the
water is heating up, cut your tomatoes into small chunks, mincing your
garlic and shallots. 

Add your pasta when the water begins to boil. In another pan, turn the
hob onto medium. When the pan is hot add your olive oil and your mise
en place. Be careful not to burn the garlic, otherwise it'll end up
coming out bitter. If you like heat, add crushed chillis. When the
pasta is slightly less than al dente, transfer over to the pan. Be
sure to scoop in some pasta water. The starch rich water adds flavour
and also helps to thicken the sauce if it's watery.

Break apart and add the smoked salmon into the pan along with the dill
and lemon. Continue stiring and cooking  until your pasta is al dente.

You want a bit of freshness to cut the smoke flavour from the
salmon. Stir in some freshly minced chives.

Serve with parmasan and some more chives for garnish.

** Notes

The version I made was a bit smokey and pasta slightly over cooked. I
misjudged the doneness of the spaghetti when I moved it over to the
pan. I only had lemon concentrate but next time I'll add lemon zest
along with capers to cut through the smokeyness. I rate it 7/10 and
would make it again.

